#!/bin/sh
set -e

lb config noauto \
    --architecture amd64 \
    --distribution bookworm \
    --binary-images iso-hybrid \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    "${@}"